<?php

namespace App\DataProviders;

abstract class CountryDataProvider
{
    public static function data(): array
    {
        return [
            ['id' => '1', 'name' => 'afghanistan', 'phone_code' => '+93'],
            ['id' => '2', 'name' => 'albania', 'phone_code' => '+355'],
            ['id' => '3', 'name' => 'algeria', 'phone_code' => '+213'],
            ['id' => '4', 'name' => 'american samoa', 'phone_code' => '+1-684'],
            ['id' => '5', 'name' => 'andorra', 'phone_code' => '+376'],
            ['id' => '6', 'name' => 'angola', 'phone_code' => '+244'],
            ['id' => '7', 'name' => 'anguilla', 'phone_code' => '+1-264'],
            ['id' => '8', 'name' => 'antarctica', 'phone_code' => '+672'],
            ['id' => '9', 'name' => 'antigua and barbuda', 'phone_code' => '+1-268'],
            ['id' => '10', 'name' => 'argentina', 'phone_code' => '+54'],
            ['id' => '11', 'name' => 'armenia', 'phone_code' => '+374'],
            ['id' => '12', 'name' => 'aruba', 'phone_code' => '+297'],
            ['id' => '13', 'name' => 'australia', 'phone_code' => '+61'],
            ['id' => '14', 'name' => 'austria', 'phone_code' => '+43'],
            ['id' => '15', 'name' => 'azerbaijan', 'phone_code' => '+994'],
            ['id' => '16', 'name' => 'bahamas the', 'phone_code' => '+1-242'],
            ['id' => '17', 'name' => 'bahrain', 'phone_code' => '+973'],
            ['id' => '18', 'name' => 'bangladesh', 'phone_code' => '+880'],
            ['id' => '19', 'name' => 'barbados', 'phone_code' => '+1-246'],
            ['id' => '20', 'name' => 'belarus', 'phone_code' => '+375'],
            ['id' => '21', 'name' => 'belgium', 'phone_code' => '+32'],
            ['id' => '22', 'name' => 'belize', 'phone_code' => '+501'],
            ['id' => '23', 'name' => 'benin', 'phone_code' => '+229'],
            ['id' => '24', 'name' => 'bermuda', 'phone_code' => '+1-441'],
            ['id' => '25', 'name' => 'bhutan', 'phone_code' => '+975'],
            ['id' => '26', 'name' => 'bolivia', 'phone_code' => '+591'],
            ['id' => '27', 'name' => 'bosnia and herzegovina', 'phone_code' => '+387'],
            ['id' => '28', 'name' => 'botswana', 'phone_code' => '+267'],
            ['id' => '29', 'name' => 'bouvet island', 'phone_code' => '+55'],
            ['id' => '30', 'name' => 'brazil', 'phone_code' => '+55'],
            ['id' => '31', 'name' => 'british indian ocean territory', 'phone_code' => '+246'],
            ['id' => '32', 'name' => 'brunei', 'phone_code' => '+673'],
            ['id' => '33', 'name' => 'bulgaria', 'phone_code' => '+359'],
            ['id' => '34', 'name' => 'burkina faso', 'phone_code' => '+226'],
            ['id' => '35', 'name' => 'burundi', 'phone_code' => '+257'],
            ['id' => '36', 'name' => 'cambodia', 'phone_code' => '+855'],
            ['id' => '37', 'name' => 'cameroon', 'phone_code' => '+237'],
            ['id' => '38', 'name' => 'canada', 'phone_code' => '+1'],
            ['id' => '39', 'name' => 'cape verde', 'phone_code' => '+238'],
            ['id' => '40', 'name' => 'cayman islands', 'phone_code' => '+1-345'],
            ['id' => '41', 'name' => 'central african republic', 'phone_code' => '+236'],
            ['id' => '42', 'name' => 'chad', 'phone_code' => '+235'],
            ['id' => '43', 'name' => 'chile', 'phone_code' => '+56'],
            ['id' => '44', 'name' => 'china', 'phone_code' => '+86'],
            ['id' => '45', 'name' => 'christmas island', 'phone_code' => '+61'],
            ['id' => '46', 'name' => 'cocos (keeling) islands', 'phone_code' => '+61'],
            ['id' => '47', 'name' => 'colombia', 'phone_code' => '+57'],
            ['id' => '48', 'name' => 'comoros', 'phone_code' => '+269'],
            ['id' => '49', 'name' => 'congo', 'phone_code' => '+242'],
            ['id' => '50', 'name' => 'congo the democratic republic of the', 'phone_code' => '+243'],
            ['id' => '51', 'name' => 'cook islands', 'phone_code' => '+682'],
            ['id' => '52', 'name' => 'costa rica', 'phone_code' => '+506'],
            ['id' => '53', 'name' => 'cote d\'ivoire (ivory coast)', 'phone_code' => '+225'],
            ['id' => '54', 'name' => 'croatia (hrvatska)', 'phone_code' => '+385'],
            ['id' => '55', 'name' => 'cuba', 'phone_code' => '+53'],
            ['id' => '56', 'name' => 'cyprus', 'phone_code' => '+357'],
            ['id' => '57', 'name' => 'czech republic', 'phone_code' => '+420'],
            ['id' => '58', 'name' => 'denmark', 'phone_code' => '+45'],
            ['id' => '59', 'name' => 'djibouti', 'phone_code' => '+253'],
            ['id' => '60', 'name' => 'dominica', 'phone_code' => '+1-767'],
            ['id' => '61', 'name' => 'dominican republic', 'phone_code' => '+1-809, +1-829, +1-849'],
            ['id' => '62', 'name' => 'east timor', 'phone_code' => '+670'],
            ['id' => '63', 'name' => 'ecuador', 'phone_code' => '+593'],
            ['id' => '64', 'name' => 'egypt', 'phone_code' => '+20'],
            ['id' => '65', 'name' => 'el salvador', 'phone_code' => '+503'],
            ['id' => '66', 'name' => 'equatorial guinea', 'phone_code' => '+240'],
            ['id' => '67', 'name' => 'eritrea', 'phone_code' => '+291'],
            ['id' => '68', 'name' => 'estonia', 'phone_code' => '+372'],
            ['id' => '69', 'name' => 'ethiopia', 'phone_code' => '+251'],
            ['id' => '70', 'name' => 'external territories of australia', 'phone_code' => '+61'],
            ['id' => '71', 'name' => 'falkland islands', 'phone_code' => '+500'],
            ['id' => '72', 'name' => 'faroe islands', 'phone_code' => '+298'],
            ['id' => '73', 'name' => 'fiji islands', 'phone_code' => '+679'],
            ['id' => '74', 'name' => 'finland', 'phone_code' => '+358'],
            ['id' => '75', 'name' => 'france', 'phone_code' => '+33'],
            ['id' => '76', 'name' => 'french guiana', 'phone_code' => '+594'],
            ['id' => '77', 'name' => 'french polynesia', 'phone_code' => '+689'],
            ['id' => '78', 'name' => 'french southern territories', 'phone_code' => '+262'],
            ['id' => '79', 'name' => 'gabon', 'phone_code' => '+241'],
            ['id' => '80', 'name' => 'gambia the', 'phone_code' => '+220'],
            ['id' => '81', 'name' => 'georgia', 'phone_code' => '+995'],
            ['id' => '82', 'name' => 'germany', 'phone_code' => '+49'],
            ['id' => '83', 'name' => 'ghana', 'phone_code' => '+233'],
            ['id' => '84', 'name' => 'gibraltar', 'phone_code' => '+350'],
            ['id' => '85', 'name' => 'greece', 'phone_code' => '+30'],
            ['id' => '86', 'name' => 'greenland', 'phone_code' => '+299'],
            ['id' => '87', 'name' => 'grenada', 'phone_code' => '+1-473'],
            ['id' => '88', 'name' => 'guadeloupe', 'phone_code' => '+590'],
            ['id' => '89', 'name' => 'guam', 'phone_code' => '+1-671'],
            ['id' => '90', 'name' => 'guatemala', 'phone_code' => '+502'],
            ['id' => '91', 'name' => 'guernsey and alderney', 'phone_code' => '+44'],
            ['id' => '92', 'name' => 'guinea', 'phone_code' => '+224'],
            ['id' => '93', 'name' => 'guinea-bissau', 'phone_code' => '+245'],
            ['id' => '94', 'name' => 'guyana', 'phone_code' => '+592'],
            ['id' => '95', 'name' => 'haiti', 'phone_code' => '+509'],
            ['id' => '96', 'name' => 'heard and mcdonald islands', 'phone_code' => '+672'],
            ['id' => '97', 'name' => 'honduras', 'phone_code' => '+504'],
            ['id' => '98', 'name' => 'hong kong s.a.r.', 'phone_code' => '+852'],
            ['id' => '99', 'name' => 'hungary', 'phone_code' => '+36'],
            ['id' => '100', 'name' => 'iceland', 'phone_code' => '+354'],
            ['id' => '101', 'name' => 'india', 'phone_code' => '+91'],
            ['id' => '102', 'name' => 'indonesia', 'phone_code' => '+62'],
            ['id' => '103', 'name' => 'iran', 'phone_code' => '+98'],
            ['id' => '104', 'name' => 'iraq', 'phone_code' => '+964'],
            ['id' => '105', 'name' => 'ireland', 'phone_code' => '+353'],
            ['id' => '106', 'name' => 'israel', 'phone_code' => '+972'],
            ['id' => '107', 'name' => 'italy', 'phone_code' => '+39'],
            ['id' => '108', 'name' => 'jamaica', 'phone_code' => '+1-876'],
            ['id' => '109', 'name' => 'japan', 'phone_code' => '+81'],
            ['id' => '110', 'name' => 'jersey', 'phone_code' => '+44'],
            ['id' => '111', 'name' => 'jordan', 'phone_code' => '+962'],
            ['id' => '112', 'name' => 'kazakhstan', 'phone_code' => '+7'],
            ['id' => '113', 'name' => 'kenya', 'phone_code' => '+254'],
            ['id' => '114', 'name' => 'kiribati', 'phone_code' => '+686'],
            ['id' => '115', 'name' => 'korea north', 'phone_code' => '+850'],
            ['id' => '116', 'name' => 'korea south', 'phone_code' => '+82'],
            ['id' => '117', 'name' => 'kuwait', 'phone_code' => '+965'],
            ['id' => '118', 'name' => 'kyrgyzstan', 'phone_code' => '+996'],
            ['id' => '119', 'name' => 'laos', 'phone_code' => '+856'],
            ['id' => '120', 'name' => 'latvia', 'phone_code' => '+371'],
            ['id' => '121', 'name' => 'lebanon', 'phone_code' => '+961'],
            ['id' => '122', 'name' => 'lesotho', 'phone_code' => '+266'],
            ['id' => '123', 'name' => 'liberia', 'phone_code' => '+231'],
            ['id' => '124', 'name' => 'libya', 'phone_code' => '+218'],
            ['id' => '125', 'name' => 'liechtenstein', 'phone_code' => '+423'],
            ['id' => '126', 'name' => 'lithuania', 'phone_code' => '+370'],
            ['id' => '127', 'name' => 'luxembourg', 'phone_code' => '+352'],
            ['id' => '128', 'name' => 'macau s.a.r.', 'phone_code' => '+853'],
            ['id' => '129', 'name' => 'macedonia', 'phone_code' => '+389'],
            ['id' => '130', 'name' => 'madagascar', 'phone_code' => '+261'],
            ['id' => '131', 'name' => 'malawi', 'phone_code' => '+265'],
            ['id' => '132', 'name' => 'malaysia', 'phone_code' => '+60'],
            ['id' => '133', 'name' => 'maldives', 'phone_code' => '+960'],
            ['id' => '134', 'name' => 'mali', 'phone_code' => '+223'],
            ['id' => '135', 'name' => 'malta', 'phone_code' => '+356'],
            ['id' => '136', 'name' => 'man (isle of)', 'phone_code' => '+44'],
            ['id' => '137', 'name' => 'marshall islands', 'phone_code' => '+692'],
            ['id' => '138', 'name' => 'martinique', 'phone_code' => '+596'],
            ['id' => '139', 'name' => 'mauritania', 'phone_code' => '+222'],
            ['id' => '140', 'name' => 'mauritius', 'phone_code' => '+230'],
            ['id' => '141', 'name' => 'mayotte', 'phone_code' => '+262'],
            ['id' => '142', 'name' => 'mexico', 'phone_code' => '+52'],
            ['id' => '143', 'name' => 'micronesia', 'phone_code' => '+691'],
            ['id' => '144', 'name' => 'moldova', 'phone_code' => '+373'],
            ['id' => '145', 'name' => 'monaco', 'phone_code' => '+377'],
            ['id' => '146', 'name' => 'mongolia', 'phone_code' => '+976'],
            
            ['id' => '147', 'name' => 'montserrat', 'phone_code' => '+1-664'],
            ['id' => '148', 'name' => 'morocco', 'phone_code' => '+212'],
            ['id' => '149', 'name' => 'mozambique', 'phone_code' => '+258'],
            ['id' => '150', 'name' => 'myanmar', 'phone_code' => '+95'],
            ['id' => '151', 'name' => 'namibia', 'phone_code' => '+264'],
            ['id' => '152', 'name' => 'nauru', 'phone_code' => '+674'],
            ['id' => '153', 'name' => 'nepal', 'phone_code' => '+977'],
            ['id' => '154', 'name' => 'netherlands antilles', 'phone_code' => '+599'],
            ['id' => '155', 'name' => 'netherlands the', 'phone_code' => '+31'],
            ['id' => '156', 'name' => 'new caledonia', 'phone_code' => '+687'],
            ['id' => '157', 'name' => 'new zealand', 'phone_code' => '+64'],
            ['id' => '158', 'name' => 'nicaragua', 'phone_code' => '+505'],
            ['id' => '159', 'name' => 'niger', 'phone_code' => '+227'],
            ['id' => '160', 'name' => 'nigeria', 'phone_code' => '+234'],
            ['id' => '161', 'name' => 'niue', 'phone_code' => '+683'],
            ['id' => '162', 'name' => 'norfolk island', 'phone_code' => '+672'],
            ['id' => '163', 'name' => 'northern mariana islands', 'phone_code' => '+1-670'],
            ['id' => '164', 'name' => 'norway', 'phone_code' => '+47'],
            ['id' => '165', 'name' => 'oman', 'phone_code' => '+968'],
            ['id' => '166', 'name' => 'pakistan', 'phone_code' => '+92'],
            ['id' => '167', 'name' => 'palau', 'phone_code' => '+680'],
            ['id' => '168', 'name' => 'palestinian territory occupied', 'phone_code' => '+970'],
            ['id' => '169', 'name' => 'panama', 'phone_code' => '+507'],
            ['id' => '170', 'name' => 'papua new guinea', 'phone_code' => '+675'],
            ['id' => '171', 'name' => 'paraguay', 'phone_code' => '+595'],
            ['id' => '172', 'name' => 'peru', 'phone_code' => '+51'],
            ['id' => '173', 'name' => 'philippines', 'phone_code' => '+63'],
            ['id' => '174', 'name' => 'pitcairn island', 'phone_code' => '+870'],
            ['id' => '175', 'name' => 'poland', 'phone_code' => '+48'],
            ['id' => '176', 'name' => 'portugal', 'phone_code' => '+351'],
            ['id' => '177', 'name' => 'puerto rico', 'phone_code' => '+1-787 and 1-939'],
            ['id' => '178', 'name' => 'qatar', 'phone_code' => '+974'],
            ['id' => '179', 'name' => 'reunion', 'phone_code' => '+262'],
            ['id' => '180', 'name' => 'romania', 'phone_code' => '+40'],
            ['id' => '181', 'name' => 'russia', 'phone_code' => '+7'],
            ['id' => '182', 'name' => 'rwanda', 'phone_code' => '+250'],
            ['id' => '183', 'name' => 'saint helena', 'phone_code' => '+290'],
            ['id' => '184', 'name' => 'saint kitts and nevis', 'phone_code' => '+1-869'],
            ['id' => '185', 'name' => 'saint lucia', 'phone_code' => '+1-758'],
            ['id' => '186', 'name' => 'saint pierre and miquelon', 'phone_code' => '+508'],
            ['id' => '187', 'name' => 'saint vincent and the grenadines', 'phone_code' => '+1-784'],
            ['id' => '188', 'name' => 'samoa', 'phone_code' => '+685'],
            ['id' => '189', 'name' => 'san marino', 'phone_code' => '+378'],
            ['id' => '190', 'name' => 'sao tome and principe', 'phone_code' => '+239'],
            ['id' => '191', 'name' => 'saudi arabia', 'phone_code' => '+966'],
            ['id' => '192', 'name' => 'senegal', 'phone_code' => '+221'],
            ['id' => '193', 'name' => 'serbia', 'phone_code' => '+381'],
            ['id' => '194', 'name' => 'seychelles', 'phone_code' => '+248'],
            ['id' => '195', 'name' => 'sierra leone', 'phone_code' => '+232'],
            ['id' => '196', 'name' => 'singapore', 'phone_code' => '+65'],
            ['id' => '197', 'name' => 'slovakia', 'phone_code' => '+421'],
            ['id' => '198', 'name' => 'slovenia', 'phone_code' => '+386'],
            ['id' => '199', 'name' => 'smaller territories of the uk', 'phone_code' => '+44'],
            ['id' => '200', 'name' => 'solomon islands', 'phone_code' => '+677'],
            ['id' => '201', 'name' => 'somalia', 'phone_code' => '+252'],
            ['id' => '202', 'name' => 'south africa', 'phone_code' => '+27'],
            ['id' => '203', 'name' => 'south georgia', 'phone_code' => '+500'],
            ['id' => '204', 'name' => 'south sudan', 'phone_code' => '+211'],
            ['id' => '205', 'name' => 'spain', 'phone_code' => '+34'],
            ['id' => '206', 'name' => 'sri lanka', 'phone_code' => '+94'],
            ['id' => '207', 'name' => 'sudan', 'phone_code' => '+249'],
            ['id' => '208', 'name' => 'suriname', 'phone_code' => '+597'],
            ['id' => '209', 'name' => 'svalbard and jan mayen islands', 'phone_code' => '+47'],
            ['id' => '210', 'name' => 'swaziland', 'phone_code' => '+268'],
            ['id' => '211', 'name' => 'sweden', 'phone_code' => '+46'],
            ['id' => '212', 'name' => 'switzerland', 'phone_code' => '+41'],
            ['id' => '213', 'name' => 'syria', 'phone_code' => '+963'],
            ['id' => '214', 'name' => 'taiwan', 'phone_code' => '+886'],
            ['id' => '215', 'name' => 'tajikistan', 'phone_code' => '+992'],
            ['id' => '216', 'name' => 'tanzania', 'phone_code' => '+255'],
            ['id' => '217', 'name' => 'thailand', 'phone_code' => '+66'],
            ['id' => '218', 'name' => 'togo', 'phone_code' => '+228'],
            ['id' => '219', 'name' => 'tokelau', 'phone_code' => '+690'],
            ['id' => '220', 'name' => 'tonga', 'phone_code' => '+676'],
            ['id' => '221', 'name' => 'trinidad and tobago', 'phone_code' => '+1-868'],
            ['id' => '222', 'name' => 'tunisia', 'phone_code' => '+216'],
            ['id' => '223', 'name' => 'turkey', 'phone_code' => '+90'],
            ['id' => '224', 'name' => 'turkmenistan', 'phone_code' => '+993'],
            ['id' => '225', 'name' => 'turks and caicos islands', 'phone_code' => '+1-649'],
            ['id' => '226', 'name' => 'tuvalu', 'phone_code' => '+688'],
            ['id' => '227', 'name' => 'uganda', 'phone_code' => '+256'],
            ['id' => '228', 'name' => 'ukraine', 'phone_code' => '+380'],
            ['id' => '229', 'name' => 'united arab emirates', 'phone_code' => '+971'],
            ['id' => '230', 'name' => 'united kingdom', 'phone_code' => '+44'],
            ['id' => '231', 'name' => 'united states', 'phone_code' => '+1'],
            ['id' => '233', 'name' => 'uruguay', 'phone_code' => '+598'],
            ['id' => '234', 'name' => 'uzbekistan', 'phone_code' => '+998'],
            ['id' => '235', 'name' => 'vanuatu', 'phone_code' => '+678'],
            ['id' => '236', 'name' => 'vatican city state (holy see)', 'phone_code' => '+379'],
            ['id' => '237', 'name' => 'venezuela', 'phone_code' => '+58'],
            ['id' => '238', 'name' => 'vietnam', 'phone_code' => '+84'],
            ['id' => '239', 'name' => 'virgin islands (british)', 'phone_code' => '+1-284'],
            ['id' => '240', 'name' => 'virgin islands (u.s.)', 'phone_code' => '+1-340'],
            ['id' => '241', 'name' => 'wallis and futuna islands', 'phone_code' => '+681'],
            ['id' => '242', 'name' => 'western sahara', 'phone_code' => '+212'],
            ['id' => '243', 'name' => 'yemen', 'phone_code' => '+967'],
            ['id' => '245', 'name' => 'zambia', 'phone_code' => '+260'],
            ['id' => '246', 'name' => 'zimbabwe', 'phone_code' => '+263'],
        ];
    }
}
