<?php

namespace App\DataProviders;

abstract class StockDataProvider
{
    public static function data(): array
    {
        return [
                    ['symbol' => 'AAPL', 'name' => 'Apple Inc.', 'img' => 'https://cdn.freebiesupply.com/images/large/2x/apple-logo-transparent.png'],
                    ['symbol' => 'GOOGL', 'name' => 'Alphabet Inc.', 'img' => 'https://cdn1.iconfinder.com/data/icons/google-s-logo/150/Google_Icons-09-512.png'],
                    ['symbol' => 'AMZN', 'name' => 'Amazon.com, Inc.', 'img' => 'https://cdn0.iconfinder.com/data/icons/most-usable-logos/120/Amazon-512.png'],
                    ['symbol' => 'MSFT', 'name' => 'Microsoft Corporation', 'img' => 'https://ed-alliance.org/wp-content/uploads/2020/08/logo-microsoft-corporation-brand-windows-server-2016-windows-xp-png-favpng-MfQ9Eh8taScufiz3KRPuRSLjd.png'],
                    ['symbol' => 'TSLA', 'name' => 'Tesla, Inc.', 'img' => 'https://static.vecteezy.com/system/resources/previews/020/975/670/non_2x/tesla-logo-tesla-icon-transparent-free-png.png'],
                    ['symbol' => 'FB', 'name' => 'Facebook, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Facebook_Logo_2023.png/768px-Facebook_Logo_2023.png'],
                    ['symbol' => 'NFLX', 'name' => 'Netflix, Inc.', 'img' => 'https://static.vecteezy.com/system/resources/previews/017/396/804/non_2x/netflix-mobile-application-logo-free-png.png'],
                    ['symbol' => 'NVDA', 'name' => 'NVIDIA Corporation', 'img' => 'https://seeklogo.com/images/N/nvidia-logo-2B71F1828F-seeklogo.com.png'],
                    ['symbol' => 'BABA', 'name' => 'Alibaba Group Holding Limited', 'img' => 'https://logolook.net/wp-content/uploads/2023/10/Alibaba-Logo.png'],
                    ['symbol' => 'V', 'name' => 'Visa Inc.', 'img' => 'https://static.vecteezy.com/system/resources/previews/020/975/576/non_2x/visa-logo-visa-icon-transparent-free-png.png'],
                    ['symbol' => 'JNJ', 'name' => 'Johnson & Johnson', 'img' => 'https://www.pngall.com/wp-content/uploads/15/Johnson-And-Johnson-Logo-PNG-Photos.png'],
                    ['symbol' => 'WMT', 'name' => 'Walmart Inc.', 'img' => 'https://cdn.freebiesupply.com/logos/thumbs/2x/walmart-logo.png'],
                    ['symbol' => 'PG', 'name' => 'Procter & Gamble Co.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/f/f9/P%26G_logo.png'],
                    ['symbol' => 'DIS', 'name' => 'The Walt Disney Company', 'img' => 'https://pngimg.com/d/walt_disney_PNG28.png'],
                    ['symbol' => 'MA', 'name' => 'Mastercard Incorporated', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Mastercard-logo.svg/1200px-Mastercard-logo.svg.png'],
                    
                    ['symbol' => 'CSCO', 'name' => 'Cisco Systems, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Cisco_logo.svg/1200px-Cisco_logo.svg.png'],
                    ['symbol' => 'ORCL', 'name' => 'Oracle Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Oracle_logo.svg/1200px-Oracle_logo.svg.png'],
                    ['symbol' => 'INTC', 'name' => 'Intel Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Intel-logo.svg/1200px-Intel-logo.svg.png'],
                    ['symbol' => 'ADBE', 'name' => 'Adobe Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Adobe_Corporate_Logo.svg/1200px-Adobe_Corporate_Logo.svg.png'],
                    ['symbol' => 'CMCSA', 'name' => 'Comcast Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Comcast_Logo.svg/1200px-Comcast_Logo.svg.png'],
                    ['symbol' => 'NFLX', 'name' => 'Netflix, Inc.', 'img' => 'https://static.vecteezy.com/system/resources/previews/017/396/804/non_2x/netflix-mobile-application-logo-free-png.png'],
                    ['symbol' => 'PYPL', 'name' => 'PayPal Holdings, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/PayPal_logo_2014.svg/1200px-PayPal_logo_2014.svg.png'],
                    ['symbol' => 'T', 'name' => 'AT&T Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/AT%26T_logo_2016.svg/1200px-AT%26T_logo_2016.svg.png'],
                    ['symbol' => 'PFE', 'name' => 'Pfizer Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Pfizer_logo.svg/1200px-Pfizer_logo.svg.png'],
                    ['symbol' => 'VZ', 'name' => 'Verizon Communications Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Verizon-logo.svg/1200px-Verizon-logo.svg.png'],
                    ['symbol' => 'KO', 'name' => 'The Coca-Cola Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Coca-Cola_logo.svg/1200px-Coca-Cola_logo.svg.png'],
                    ['symbol' => 'NKE', 'name' => 'NIKE, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Nike_logo.svg/1200px-Nike_logo.svg.png'],
                    ['symbol' => 'PEP', 'name' => 'PepsiCo, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Pepsi_logo_2014.svg/1200px-Pepsi_logo_2014.svg.png'],
                    ['symbol' => 'MRK', 'name' => 'Merck & Co., Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Merck_Logo.svg/1200px-Merck_Logo.svg.png'],
                    ['symbol' => 'AVGO', 'name' => 'Broadcom Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Broadcom_Logo.svg/1200px-Broadcom_Logo.svg.png'],
                    ['symbol' => 'TXN', 'name' => 'Texas Instruments Incorporated', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Texas_Instruments_logo.svg/1200px-Texas_Instruments_logo.svg.png'],
                    ['symbol' => 'QCOM', 'name' => 'Qualcomm Incorporated', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Qualcomm_logo.svg/1200px-Qualcomm_logo.svg.png'],
                    ['symbol' => 'IBM', 'name' => 'International Business Machines Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/IBM_logo.svg/1200px-IBM_logo.svg.png'],
                    ['symbol' => 'TMO', 'name' => 'Thermo Fisher Scientific Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Thermo_Fisher_Scientific_Logo.svg/1200px-Thermo_Fisher_Scientific_Logo.svg.png'],
                    ['symbol' => 'MDT', 'name' => 'Medtronic plc', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Medtronic_logo.svg/1200px-Medtronic_logo.svg.png'],
                    ['symbol' => 'AMGN', 'name' => 'Amgen Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Amgen_logo.svg/1200px-Amgen_logo.svg.png'],
                    ['symbol' => 'LMT', 'name' => 'Lockheed Martin Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Lockheed_Martin_logo.svg/1200px-Lockheed_Martin_logo.svg.png'],
                    ['symbol' => 'CAT', 'name' => 'Caterpillar Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Caterpillar_Inc_logo.svg/1200px-Caterpillar_Inc_logo.svg.png'],
                    ['symbol' => 'BA', 'name' => 'The Boeing Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Boeing_logo.svg/1200px-Boeing_logo.svg.png'],
                    ['symbol' => 'LRCX', 'name' => 'Lam Research Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Lam_Research_Logo.svg/1200px-Lam_Research_Logo.svg.png'],
                    ['symbol' => 'SBUX', 'name' => 'Starbucks Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Starbucks_Logo.svg/1200px-Starbucks_Logo.svg.png'],
                    ['symbol' => 'CSX', 'name' => 'CSX Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/CSX_logo.svg/1200px-CSX_logo.svg.png'],
                    ['symbol' => 'HIG', 'name' => 'The Hartford Financial Services Group, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/The_Hartford_logo.svg/1200px-The_Hartford_logo.svg.png'],
                    ['symbol' => 'AON', 'name' => 'Aon plc', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Aon_logo.svg/1200px-Aon_logo.svg.png'],
                    ['symbol' => 'BMY', 'name' => 'Bristol-Myers Squibb Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Bristol-Myers_Squibb_logo.svg/1200px-Bristol-Myers_Squibb_logo.svg.png'],
                    ['symbol' => 'SHW', 'name' => 'Sherwin-Williams Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Sherwin_Williams_Logo.svg/1200px-Sherwin_Williams_Logo.svg.png'],
                    ['symbol' => 'COF', 'name' => 'Capital One Financial Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Capital_One_logo.svg/1200px-Capital_One_logo.svg.png'],
                    ['symbol' => 'NEM', 'name' => 'Newmont Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Newmont_Goldcorp_logo.svg/1200px-Newmont_Goldcorp_logo.svg.png'],
                    ['symbol' => 'SPGI', 'name' => 'S&P Global Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/S%26P_Global_logo.svg/1200px-S%26P_Global_logo.svg.png'],
                    ['symbol' => 'ZTS', 'name' => 'Zoetis Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Zoetis_logo.svg/1200px-Zoetis_logo.svg.png'],
                    ['symbol' => 'ICE', 'name' => 'Intercontinental Exchange, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/ICE_logo.svg/1200px-ICE_logo.svg.png'],
                    ['symbol' => 'MS', 'name' => 'Morgan Stanley', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Morgan_Stanley_logo.svg/1200px-Morgan_Stanley_logo.svg.png'],
                    ['symbol' => 'WBA', 'name' => 'Walgreens Boots Alliance, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Walgreens_logo.svg/1200px-Walgreens_logo.svg.png'],
                    ['symbol' => 'FISV', 'name' => 'FISV', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/FISV_logo.svg/1200px-FISV_logo.svg.png'],
                    ['symbol' => 'GIS', 'name' => 'General Mills, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/General_Mills_logo.svg/1200px-General_Mills_logo.svg.png'],

                    ['symbol' => 'MMM', 'name' => '3M Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/3M_Logo.svg/1200px-3M_Logo.svg.png'],
                    ['symbol' => 'AXP', 'name' => 'American Express Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/American_Express_logo.svg/1200px-American_Express_logo.svg.png'],
                    ['symbol' => 'AAPL', 'name' => 'Apple Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/1200px-Apple_logo_black.svg.png'],
                    ['symbol' => 'BA', 'name' => 'Boeing Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Boeing_logo.svg/1200px-Boeing_logo.svg.png'],
                    ['symbol' => 'CAT', 'name' => 'Caterpillar Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Caterpillar_Inc_logo.svg/1200px-Caterpillar_Inc_logo.svg.png'],
                    ['symbol' => 'CSCO', 'name' => 'Cisco Systems, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Cisco_logo.svg/1200px-Cisco_logo.svg.png'],
                    ['symbol' => 'C', 'name' => 'Citigroup Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Citigroup_logo.svg/1200px-Citigroup_logo.svg.png'],
                    ['symbol' => 'CL', 'name' => 'Colgate-Palmolive Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Colgate_logo.svg/1200px-Colgate_logo.svg.png'],
                    ['symbol' => 'DIS', 'name' => 'The Walt Disney Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/The_Walt_Disney_Company_logo.svg/1200px-The_Walt_Disney_Company_logo.svg.png'],
                    ['symbol' => 'DOW', 'name' => 'Dow Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Dow_Chemical_Company_logo.svg/1200px-Dow_Chemical_Company_logo.svg.png'],
                    ['symbol' => 'XOM', 'name' => 'Exxon Mobil Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Exxon_Mobil_logo.svg/1200px-Exxon_Mobil_logo.svg.png'],
                    ['symbol' => 'GS', 'name' => 'Goldman Sachs Group, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Goldman_Sachs_logo.svg/1200px-Goldman_Sachs_logo.svg.png'],
                    ['symbol' => 'HD', 'name' => 'The Home Depot, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Home_Depot_logo.svg/1200px-Home_Depot_logo.svg.png'],
                    ['symbol' => 'HON', 'name' => 'Honeywell International Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Honeywell_International_Logo.svg/1200px-Honeywell_International_Logo.svg.png'],
                    ['symbol' => 'IBM', 'name' => 'International Business Machines Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/IBM_logo.svg/1200px-IBM_logo.svg.png'],
                    ['symbol' => 'JNJ', 'name' => 'Johnson & Johnson', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Johnson_%26_Johnson_logo.svg/1200px-Johnson_%26_Johnson_logo.svg.png'],
                    ['symbol' => 'KMB', 'name' => 'Kimberly-Clark Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Kimberly-Clark_logo.svg/1200px-Kimberly-Clark_logo.svg.png'],
                    ['symbol' => 'MCD', 'name' => 'McDonald\'s Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/McDonald%27s_logo.svg/1200px-McDonald%27s_logo.svg.png'],
                    ['symbol' => 'MDT', 'name' => 'Medtronic plc', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Medtronic_logo.svg/1200px-Medtronic_logo.svg.png'],
                    ['symbol' => 'MRK', 'name' => 'Merck & Co., Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Merck_%26_Co._logo.svg/1200px-Merck_%26_Co._logo.svg.png'],
                    ['symbol' => 'MSFT', 'name' => 'Microsoft Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/1200px-Microsoft_logo.svg.png'],
                    ['symbol' => 'NFLX', 'name' => 'Netflix, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Netflix_logo.svg/1200px-Netflix_logo.svg.png'],
                    ['symbol' => 'PEP', 'name' => 'PepsiCo, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Pepsi_logo.svg/1200px-Pepsi_logo.svg.png'],
                    ['symbol' => 'PFE', 'name' => 'Pfizer Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Pfizer_logo.svg/1200px-Pfizer_logo.svg.png'],
                    ['symbol' => 'PG', 'name' => 'Procter & Gamble Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Procter_%26_Gamble_logo.svg/1200px-Procter_%26_Gamble_logo.svg.png'],
                    ['symbol' => 'QCOM', 'name' => 'Qualcomm Incorporated', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Qualcomm_logo.svg/1200px-Qualcomm_logo.svg.png'],
                    ['symbol' => 'RTX', 'name' => 'Raytheon Technologies Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Raytheon_Technologies_Logo.svg/1200px-Raytheon_Technologies_Logo.svg.png'],
                    ['symbol' => 'SBUX', 'name' => 'Starbucks Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Starbucks_Logo.svg/1200px-Starbucks_Logo.svg.png'],
                    ['symbol' => 'T', 'name' => 'AT&T Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/AT%26T_logo.svg/1200px-AT%26T_logo.svg.png'],
                    ['symbol' => 'TGT', 'name' => 'Target Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Target_logo.svg/1200px-Target_logo.svg.png'],
                    ['symbol' => 'TSLA', 'name' => 'Tesla, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Tesla_logo.svg/1200px-Tesla_logo.svg.png'],
                    ['symbol' => 'UNH', 'name' => 'UnitedHealth Group Incorporated', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/UnitedHealth_Group_logo.svg/1200px-UnitedHealth_Group_logo.svg.png'],
                    ['symbol' => 'V', 'name' => 'Visa Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Visa_Inc._logo.svg/1200px-Visa_Inc._logo.svg.png'],
                    ['symbol' => 'VZ', 'name' => 'Verizon Communications Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Verizon_Communications_logo.svg/1200px-Verizon_Communications_logo.svg.png'],
                    ['symbol' => 'WMT', 'name' => 'Walmart Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Walmart_logo.svg/1200px-Walmart_logo.svg.png'],
                    ['symbol' => 'WFC', 'name' => 'Wells Fargo & Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Wells_Fargo_Logo.svg/1200px-Wells_Fargo_Logo.svg.png'],
                    ['symbol' => 'XRX', 'name' => 'Xerox Holdings Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Xerox_logo.svg/1200px-Xerox_logo.svg.png'],
                    ['symbol' => 'ZM', 'name' => 'Zoom Video Communications, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Zoom_Logo.svg/1200px-Zoom_Logo.svg.png'],
                    ['symbol' => 'CSX', 'name' => 'CSX Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/CSX_Logo.svg/1200px-CSX_Logo.svg.png'],
                    ['symbol' => 'NKE', 'name' => 'Nike, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Nike_logo.svg/1200px-Nike_logo.svg.png'],
                    ['symbol' => 'ABT', 'name' => 'Abbott Laboratories', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Abbott_Laboratories_logo.svg/1200px-Abbott_Laboratories_logo.svg.png'],
                    ['symbol' => 'SYK', 'name' => 'Stryker Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Stryker_Corporation_logo.svg/1200px-Stryker_Corporation_logo.svg.png'],
                    ['symbol' => 'LLY', 'name' => 'Eli Lilly and Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Eli_Lilly_and_Company_logo.svg/1200px-Eli_Lilly_and_Company_logo.svg.png'],
                    ['symbol' => 'MDLZ', 'name' => 'Mondelez International, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Mondelez_logo.svg/1200px-Mondelez_logo.svg.png'],
                    ['symbol' => 'COST', 'name' => 'Costco Wholesale Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Costco_Wholesale_logo.svg/1200px-Costco_Wholesale_logo.svg.png'],
                    ['symbol' => 'K', 'name' => 'Kellogg Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Kellogg%27s_logo.svg/1200px-Kellogg%27s_logo.svg.png'],
                    ['symbol' => 'SYY', 'name' => 'Sysco Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Sysco_Logo.svg/1200px-Sysco_Logo.svg.png'],

                    ['symbol' => 'AFL', 'name' => 'Aflac Incorporated', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Aflac_logo.svg/1200px-Aflac_logo.svg.png'],
                    ['symbol' => 'AIG', 'name' => 'American International Group, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/AIG_logo.svg/1200px-AIG_logo.svg.png'],
                    ['symbol' => 'APD', 'name' => 'Air Products and Chemicals, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Air_Products_and_Chemicals_logo.svg/1200px-Air_Products_and_Chemicals_logo.svg.png'],
                    ['symbol' => 'AMGN', 'name' => 'Amgen Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Amgen_logo.svg/1200px-Amgen_logo.svg.png'],
                    ['symbol' => 'AXP', 'name' => 'American Express Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/American_Express_logo.svg/1200px-American_Express_logo.svg.png'],
                    ['symbol' => 'BK', 'name' => 'The Bank of New York Mellon Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/BNY_Mellon_logo.svg/1200px-BNY_Mellon_logo.svg.png'],
                    ['symbol' => 'BMY', 'name' => 'Bristol Myers Squibb Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Bristol_Myers_Squibb_logo.svg/1200px-Bristol_Myers_Squibb_logo.svg.png'],
                    ['symbol' => 'CDK', 'name' => 'CDK Global, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3f/CDK_Global_logo.svg/1200px-CDK_Global_logo.svg.png'],
                    ['symbol' => 'CME', 'name' => 'CME Group Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/CME_Group_logo.svg/1200px-CME_Group_logo.svg.png'],
                    ['symbol' => 'DHR', 'name' => 'Danaher Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Danaher_Corporation_logo.svg/1200px-Danaher_Corporation_logo.svg.png'],
                    ['symbol' => 'EFX', 'name' => 'Equifax Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Equifax_logo.svg/1200px-Equifax_logo.svg.png'],
                    ['symbol' => 'FB', 'name' => 'Meta Platforms, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Meta_Platfroms_logo.svg/1200px-Meta_Platfroms_logo.svg.png'],
                    ['symbol' => 'GLW', 'name' => 'Corning Incorporated', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Corning_Inc_Logo.svg/1200px-Corning_Inc_Logo.svg.png'],
                    ['symbol' => 'HIG', 'name' => 'The Hartford', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/The_Hartford_Logo.svg/1200px-The_Hartford_Logo.svg.png'],
                    ['symbol' => 'ISRG', 'name' => 'Intuitive Surgical, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Intuitive_Surgical_Logo.svg/1200px-Intuitive_Surgical_Logo.svg.png'],
                    ['symbol' => 'KMI', 'name' => 'Kinder Morgan, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Kinder_Morgan_logo.svg/1200px-Kinder_Morgan_logo.svg.png'],
                    ['symbol' => 'LMT', 'name' => 'Lockheed Martin Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Lockheed_Martin_logo.svg/1200px-Lockheed_Martin_logo.svg.png'],
                    ['symbol' => 'MAR', 'name' => 'Marriott International, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Marriott_International_logo.svg/1200px-Marriott_International_logo.svg.png'],
                    ['symbol' => 'NTRS', 'name' => 'Northern Trust Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Northern_Trust_logo.svg/1200px-Northern_Trust_logo.svg.png'],
                    ['symbol' => 'ORCL', 'name' => 'Oracle Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Oracle_logo.svg/1200px-Oracle_logo.svg.png'],
                    ['symbol' => 'PLD', 'name' => 'Prologis, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Prologis_logo.svg/1200px-Prologis_logo.svg.png'],
                    ['symbol' => 'RMD', 'name' => 'ResMed Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/ResMed_logo.svg/1200px-ResMed_logo.svg.png'],
                    ['symbol' => 'SHW', 'name' => 'The Sherwin-Williams Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Sherwin-Williams_logo.svg/1200px-Sherwin-Williams_logo.svg.png'],
                    ['symbol' => 'SLB', 'name' => 'Schlumberger Limited', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Schlumberger_logo.svg/1200px-Schlumberger_logo.svg.png'],
                    ['symbol' => 'SPG', 'name' => 'Simon Property Group, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Simon_Logo.svg/1200px-Simon_Logo.svg.png'],
                    ['symbol' => 'SYK', 'name' => 'Stryker Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Stryker_Corporation_logo.svg/1200px-Stryker_Corporation_logo.svg.png'],
                    ['symbol' => 'TROW', 'name' => 'T. Rowe Price Group, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/T._Rowe_Price_logo.svg/1200px-T._Rowe_Price_logo.svg.png'],
                    ['symbol' => 'WBA', 'name' => 'Walgreens Boots Alliance, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Walgreens_Boots_Alliance_logo.svg/1200px-Walgreens_Boots_Alliance_logo.svg.png'],
                    ['symbol' => 'WDC', 'name' => 'Western Digital Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Western_Digital_logo.svg/1200px-Western_Digital_logo.svg.png'],
                    ['symbol' => 'WST', 'name' => 'West Pharmaceutical Services, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/West_Pharmaceutical_Services_logo.svg/1200px-West_Pharmaceutical_Services_logo.svg.png'],
                    ['symbol' => 'ZTS', 'name' => 'Zoetis Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Zoetis_logo.svg/1200px-Zoetis_logo.svg.png'],
                    ['symbol' => 'NDAQ', 'name' => 'Nasdaq, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Nasdaq_logo.svg/1200px-Nasdaq_logo.svg.png'],
                    ['symbol' => 'AMT', 'name' => 'American Tower Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/American_Tower_Logo.svg/1200px-American_Tower_Logo.svg.png'],
                    ['symbol' => 'ADBE', 'name' => 'Adobe Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Adobe_Logo.svg/1200px-Adobe_Logo.svg.png'],
                    ['symbol' => 'BAX', 'name' => 'Baxter International Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Baxter_International_Logo.svg/1200px-Baxter_International_Logo.svg.png'],
                    ['symbol' => 'CARR', 'name' => 'Carrier Global Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Carrier_Global_Logo.svg/1200px-Carrier_Global_Logo.svg.png'],
                    ['symbol' => 'FIS', 'name' => 'FIS Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/FIS_logo.svg/1200px-FIS_logo.svg.png'],
                    ['symbol' => 'HST', 'name' => 'Host Hotels & Resorts, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Host_Hotels_%26_Resorts_Logo.svg/1200px-Host_Hotels_%26_Resorts_Logo.svg.png'],
                    ['symbol' => 'KMX', 'name' => 'CarMax, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/CarMax_logo.svg/1200px-CarMax_logo.svg.png'],
                    ['symbol' => 'NKE', 'name' => 'Nike, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Nike_logo.svg/1200px-Nike_logo.svg.png'],

                    ['symbol' => 'ABBV', 'name' => 'AbbVie Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/AbbVie_logo.svg/1200px-AbbVie_logo.svg.png'],
                    ['symbol' => 'ADP', 'name' => 'Automatic Data Processing, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Automatic_Data_Processing_logo.svg/1200px-Automatic_Data_Processing_logo.svg.png'],
                    ['symbol' => 'AON', 'name' => 'Aon plc', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Aon_logo.svg/1200px-Aon_logo.svg.png'],
                    ['symbol' => 'AAPL', 'name' => 'Apple Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/1200px-Apple_logo_black.svg.png'],
                    ['symbol' => 'BMY', 'name' => 'Bristol Myers Squibb Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Bristol_Myers_Squibb_logo.svg/1200px-Bristol_Myers_Squibb_logo.svg.png'],
                    ['symbol' => 'CAH', 'name' => 'Cardinal Health, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Cardinal_Health_Logo.svg/1200px-Cardinal_Health_Logo.svg.png'],
                    ['symbol' => 'CLX', 'name' => 'The Clorox Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Clorox_Logo.svg/1200px-Clorox_Logo.svg.png'],
                    ['symbol' => 'DOV', 'name' => 'Dover Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Dover_Corporation_Logo.svg/1200px-Dover_Corporation_Logo.svg.png'],
                    ['symbol' => 'DIS', 'name' => 'The Walt Disney Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/The_Walt_Disney_Company_logo.svg/1200px-The_Walt_Disney_Company_logo.svg.png'],
                    ['symbol' => 'ED', 'name' => 'Consolidated Edison, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Consolidated_Edison_Logo.svg/1200px-Consolidated_Edison_Logo.svg.png'],
                    ['symbol' => 'FISV', 'name' => 'Fiserv, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Fiserv_logo.svg/1200px-Fiserv_logo.svg.png'],
                    ['symbol' => 'GE', 'name' => 'General Electric Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/General_Electric_logo.svg/1200px-General_Electric_logo.svg.png'],
                    ['symbol' => 'GLW', 'name' => 'Corning Incorporated', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Corning_Inc_Logo.svg/1200px-Corning_Inc_Logo.svg.png'],
                    ['symbol' => 'HRB', 'name' => 'H&R Block, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/H%26R_Block_logo.svg/1200px-H%26R_Block_logo.svg.png'],
                    ['symbol' => 'HSY', 'name' => 'The Hershey Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Hershey%27s_logo.svg/1200px-Hershey%27s_logo.svg.png'],
                    ['symbol' => 'JBHT', 'name' => 'J.B. Hunt Transport Services, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/JB_Hunt_Logo.svg/1200px-JB_Hunt_Logo.svg.png'],
                    ['symbol' => 'K', 'name' => 'Kellogg Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Kellogg%27s_logo.svg/1200px-Kellogg%27s_logo.svg.png'],
                    ['symbol' => 'KMB', 'name' => 'Kimberly-Clark Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Kimberly-Clark_Logo.svg/1200px-Kimberly-Clark_Logo.svg.png'],
                    ['symbol' => 'MPC', 'name' => 'Marathon Petroleum Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Marathon_Petroleum_logo.svg/1200px-Marathon_Petroleum_logo.svg.png'],
                    ['symbol' => 'MSI', 'name' => 'Motorola Solutions, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Motorola_Solutions_logo.svg/1200px-Motorola_Solutions_logo.svg.png'],
                    ['symbol' => 'NEM', 'name' => 'Newmont Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Newmont_logo.svg/1200px-Newmont_logo.svg.png'],
                    ['symbol' => 'NFLX', 'name' => 'Netflix, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Netflix_logo.svg/1200px-Netflix_logo.svg.png'],
                    ['symbol' => 'PH', 'name' => 'Parker-Hannifin Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Parker_Hannifin_logo.svg/1200px-Parker_Hannifin_logo.svg.png'],
                    ['symbol' => 'PPG', 'name' => 'PPG Industries, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/PPG_Industries_logo.svg/1200px-PPG_Industries_logo.svg.png'],
                    ['symbol' => 'SRE', 'name' => 'Sempra Energy', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Sempra_Energy_logo.svg/1200px-Sempra_Energy_logo.svg.png'],
                    ['symbol' => 'TAP', 'name' => 'Molson Coors Beverage Company', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Molson_Coors_Beverage_Company_logo.svg/1200px-Molson_Coors_Beverage_Company_logo.svg.png'],
                    ['symbol' => 'TPR', 'name' => 'Tapestry, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Tapestry_logo.svg/1200px-Tapestry_logo.svg.png'],
                    ['symbol' => 'VTRS', 'name' => 'Viatris Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Viatris_logo.svg/1200px-Viatris_logo.svg.png'],
                    ['symbol' => 'WAB', 'name' => 'Westinghouse Air Brake Technologies Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Wabtec_logo.svg/1200px-Wabtec_logo.svg.png'],
                    ['symbol' => 'WM', 'name' => 'Waste Management, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Waste_Management_logo.svg/1200px-Waste_Management_logo.svg.png'],
                    ['symbol' => 'XOM', 'name' => 'Exxon Mobil Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Exxon_Mobil_logo.svg/1200px-Exxon_Mobil_logo.svg.png'],
                    ['symbol' => 'YUM', 'name' => 'Yum! Brands, Inc.', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Yum_Brands_logo.svg/1200px-Yum_Brands_logo.svg.png'],
                    ['symbol' => 'ZBRA', 'name' => 'Zebra Technologies Corporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Zebra_Technologies_logo.svg/1200px-Zebra_Technologies_logo.svg.png'],
                    ['symbol' => 'ZION', 'name' => 'Zions Bancorporation', 'img' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Zions_Bancorporation_logo.svg/1200px-Zions_Bancorporation_logo.svg.png'],
                ];
    }
}
